/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BookRouteImport } from './routes/book'
import { Route as AppsRouteImport } from './routes/apps'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppsIndexRouteImport } from './routes/apps/index'
import { Route as AppsTestRouteImport } from './routes/apps/test'
import { Route as AppsAdminIndexRouteImport } from './routes/apps/admin/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRoute = AppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsIndexRoute = AppsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppsRoute,
} as any)
const AppsTestRoute = AppsTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => AppsRoute,
} as any)
const AppsAdminIndexRoute = AppsAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apps': typeof AppsRouteWithChildren
  '/book': typeof BookRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/apps/test': typeof AppsTestRoute
  '/apps/': typeof AppsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/apps/admin/': typeof AppsAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/apps/test': typeof AppsTestRoute
  '/apps': typeof AppsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/apps/admin': typeof AppsAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apps': typeof AppsRouteWithChildren
  '/book': typeof BookRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/apps/test': typeof AppsTestRoute
  '/apps/': typeof AppsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/apps/admin/': typeof AppsAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apps'
    | '/book'
    | '/login'
    | '/signup'
    | '/apps/test'
    | '/apps/'
    | '/api/auth/$'
    | '/apps/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book'
    | '/login'
    | '/signup'
    | '/apps/test'
    | '/apps'
    | '/api/auth/$'
    | '/apps/admin'
  id:
    | '__root__'
    | '/'
    | '/apps'
    | '/book'
    | '/login'
    | '/signup'
    | '/apps/test'
    | '/apps/'
    | '/api/auth/$'
    | '/apps/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppsRoute: typeof AppsRouteWithChildren
  BookRoute: typeof BookRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/': {
      id: '/apps/'
      path: '/'
      fullPath: '/apps/'
      preLoaderRoute: typeof AppsIndexRouteImport
      parentRoute: typeof AppsRoute
    }
    '/apps/test': {
      id: '/apps/test'
      path: '/test'
      fullPath: '/apps/test'
      preLoaderRoute: typeof AppsTestRouteImport
      parentRoute: typeof AppsRoute
    }
    '/apps/admin/': {
      id: '/apps/admin/'
      path: '/admin'
      fullPath: '/apps/admin/'
      preLoaderRoute: typeof AppsAdminIndexRouteImport
      parentRoute: typeof AppsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppsRouteChildren {
  AppsTestRoute: typeof AppsTestRoute
  AppsIndexRoute: typeof AppsIndexRoute
  AppsAdminIndexRoute: typeof AppsAdminIndexRoute
}

const AppsRouteChildren: AppsRouteChildren = {
  AppsTestRoute: AppsTestRoute,
  AppsIndexRoute: AppsIndexRoute,
  AppsAdminIndexRoute: AppsAdminIndexRoute,
}

const AppsRouteWithChildren = AppsRoute._addFileChildren(AppsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppsRoute: AppsRouteWithChildren,
  BookRoute: BookRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
